/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:19 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
* classdump-dyld is licensed under GPLv3, Copyright В© 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>
#include <stdbool.h>
#define BOOL bool

@class SBSApplicationShortcutService, SBSApplicationShortcutServiceFetchResult, NSString, NSURL, NSNumber, NSArray;

@interface SBFApplication : NSObject {

    SBSApplicationShortcutService* _applicationShortcutService;
    SBSApplicationShortcutServiceFetchResult* _applicationShortcutServiceFetchResult;
    double _applicationShortcutServiceFetchResultExpirationReferenceTime;
    BOOL _systemOrInternalApplication;
    NSString* _applicationBundleIdentifier;
    NSString* _displayName;
    NSURL* _bundleURL;
    NSNumber* _appStoreItemID;
    NSString* _applicationShortcutWidgetBundleIdentifier;

}

@property (nonatomic,readonly) NSString * applicationBundleIdentifier;                                             //@synthesize applicationBundleIdentifier=_applicationBundleIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * displayName;                                                             //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,readonly) NSURL * bundleURL;                                                                  //@synthesize bundleURL=_bundleURL - In the implementation block
@property (getter=isSystemOrInternalApplication,nonatomic,readonly) BOOL systemOrInternalApplication;              //@synthesize systemOrInternalApplication=_systemOrInternalApplication - In the implementation block
@property (nonatomic,readonly) NSNumber * appStoreItemID;                                                          //@synthesize appStoreItemID=_appStoreItemID - In the implementation block
@property (nonatomic,readonly) NSString * applicationShortcutWidgetBundleIdentifier;                               //@synthesize applicationShortcutWidgetBundleIdentifier=_applicationShortcutWidgetBundleIdentifier - In the implementation block
@property (nonatomic,readonly) NSArray * staticApplicationShortcutItems;
@property (nonatomic,readonly) NSArray * dynamicApplicationShortcutItems;
-(NSString *)applicationBundleIdentifier;
-(NSString *)displayName;
-(id)init;
-(NSNumber *)appStoreItemID;
-(BOOL)isSystemOrInternalApplication;
-(void)dealloc;
-(id)initWithApplicationBundleIdentifier:(id)arg1 ;
-(NSURL *)bundleURL;
-(NSArray *)dynamicApplicationShortcutItems;
-(NSString *)applicationShortcutWidgetBundleIdentifier;
-(void)_updateApplicationShortcutServiceFetchResult;
-(NSArray *)staticApplicationShortcutItems;
@end
